version: 4.0.0.{build}
os: Visual Studio 2017
environment:
  Major: 4
  Minor: 0
  Revision: 0
  COVERALLS_REPO_TOKEN:
    secure: ZUu/hqbNugncqPkxoYv3hT7hUtv2JHRQLjH/B4r/ymawzUIfaVHFOYbfxLKMQifk
configuration: Release
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: normal
test: off
artifacts:
- path: Build\*.nupkg
deploy:
- provider: Environment
  name: MyGet